name: closik
description: "Closik - Nền tảng nghe và chia sẻ nhạc trực tuyến."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.11.5

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  
  # --- HỆ THỐNG FIREBASE ---
  # Dùng để lưu trữ dữ liệu người dùng, bài hát và file mp3 trực tuyến
  firebase_core: ^4.7.0
  firebase_auth: ^6.4.0
  cloud_firestore: ^6.3.0
  firebase_storage: ^13.3.0

  # --- ĐĂNG NHẬP GOOGLE ---
  google_sign_in: ^6.1.6

  # --- PHÁT NHẠC VÀ MẠNG ---
  # just_audio hỗ trợ phát nhạc từ URL (streaming) cực mượt
  just_audio: ^0.9.36
  dio: ^5.9.2
  path_provider: ^2.1.5
  # Thanh tiến trình xịn xò cho app nhạc
  audio_video_progress_bar: ^2.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_native_splash: ^2.4.0
  flutter_launcher_icons: ^0.13.1
flutter_native_splash:
  color: "#0F0F0F"
  image: assets/logo.png
  android: true
  ios: true
  # Thêm vào cuối file pubspec.yaml
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/app_icon.png" # Đường dẫn đến ảnh logo của Khang
  # Khang có thể thêm dòng này để icon đẹp hơn trên Android mới
  adaptive_icon_background: "#0F0F0F" # Màu nền đen của Closik
  adaptive_icon_foreground: "assets/app_icon.png" # Ảnh logo chính