// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC7PVfqcBbmagIUFstz3WEy8EPIl-tn6Pw',
    appId: '1:809167332045:web:44f9a73d0acaa3e20f3f84',
    messagingSenderId: '809167332045',
    projectId: 'zing-clone-46f35',
    authDomain: 'zing-clone-46f35.firebaseapp.com',
    storageBucket: 'zing-clone-46f35.firebasestorage.app',
    measurementId: 'G-0X360E4ZN4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDJX29XzUMniTblv_yXOIeIRGVwmCDBsCc',
    appId: '1:809167332045:android:7cc4463a4409e4290f3f84',
    messagingSenderId: '809167332045',
    projectId: 'zing-clone-46f35',
    storageBucket: 'zing-clone-46f35.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyASRlyoG45xbJLxoyeIdM5dY678oTzGcy8',
    appId: '1:809167332045:ios:1e3efb89594ff36f0f3f84',
    messagingSenderId: '809167332045',
    projectId: 'zing-clone-46f35',
    storageBucket: 'zing-clone-46f35.firebasestorage.app',
    iosBundleId: 'com.example.zingClone',
  );
}
